### PR TITLE
Feature: Friendship

### PR DESCRIPTION
**Pull request by 0x1100010010**
The following features have been added:
- User index page displays friendship status and available options 
- User can create a new friendship request
- User can cancel the friendship request
- User can accept the friendship request by other user
- User can decline the friendship request by other user

### CODE REVIEW

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Request changes:full_moon:
**Hi Adeel!
Great job so far:clap::clap:. The project codebase is clean and follows best practices. However, we need to make a few changes to get this project approved:muscle:.**

**Mandatory requirements**

- [x] User model has_many :friendships ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friend.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Currently missing in the User model 

- [x] User model `has_many :inverted_friendships, class_name: "Friendship", foreign_key: "friend_id"` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friend.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Also currently missing.

- [x] User has to accept friendship request to start friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). If I click on the approve friendship, It displays a nameError. Kindly fix this.

- [x] There is a button to invite user to friendship on users list page and on single user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). We currently have a link. Make it a  button

- [x] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). If a user is not yet accepted as a friend. His/her post should not be displayed in the logged-in user timeline. Kindly fix this as every created user post is currently been displayed.

- [x] There is currently no test case in the project. Kindly add both unit and integration tests with positive and negative scenarios. 

[ Optional]
- When a new user is created. The username should be displayed on the navbar. For easy identification of the logged-in user. 

Make the above-required changes and when you are ready, request another review.
Kindly drop your questions point_down: and tag my name or ping me on slack @ Eric Enaburekhan to respond.
Happy Coding:blush:
Eric Enaburekhan

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required 🛑♻**

<hr>

Hello there, great job working on this project and on the requested changes by the previous Code Reviewer. However, there is still one more thing to do before moving on. 😊🙏

- [x] Well done creating the RSpec tests. However, there are still pending tests, please fix them.

Great job, good luck with the next, and happy coding 👨‍💻💻

**Comment by 0x1100010010** [comment]
I have tested it thoroughly, they are working fine. I am not sure why model `rspec` tests are not executed directly. Kindly execute pending tests with `rspec spec/model`

**Comment by mimipeshy** [comment]
### STATUS :APPROVED :partying_face: 

Hey there @bashforger  :wave: :wave:  good job on working on the requested changes. This project is therefore approved. Go ahead and merge. All the best in the next milestones :man_technologist: 

Regards
Peris Ndanu

**Pull request merged**
